In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import plotly.express as px

In [ ]:
df = pd.read_csv("/content/netflix_titles.csv")

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
pd.set_option('display.max_columns',None)

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
def convert_date(date_str):
    if isinstance(date_str, str):
        date_str = date_str.lstrip()
        try:
            return datetime.strptime(date_str, "%B %d, %Y")
        except ValueError:
            print(f"Warning: Could not convert '{date_str}' to datetime.")
            return None
    else:
        print(f"Warning: Input is not a string: '{date_str}'")
        return None
df['date_added'] = df['date_added'].apply(convert_date)

Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'
Warning: Input is not a string: 'nan'

In [ ]:
df_1 = df[df['date_added'].isnull()]

In [ ]:
df_1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaT,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,NaT,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaT,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaT,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaT,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaT,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaT,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaT,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaT,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaT,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [ ]:
df_1.loc[df_1.index[0], 'date_added'] = pd.to_datetime('2012-12-06')
df_1.loc[df_1.index[1], 'date_added'] = pd.to_datetime('2013-04-14')
df_1.loc[df_1.index[2], 'date_added'] = pd.to_datetime('2023-10-12')
df_1.loc[df_1.index[3], 'date_added'] = pd.to_datetime('1994-09-22')
df_1.loc[df_1.index[4], 'date_added'] = pd.to_datetime('2008-01-07')
df_1.loc[df_1.index[5], 'date_added'] = pd.to_datetime('2003-12-22')
df_1.loc[df_1.index[6], 'date_added'] = pd.to_datetime('2002-08-07')
df_1.loc[df_1.index[7], 'date_added'] = pd.to_datetime('2013-05-03')
df_1.loc[df_1.index[8], 'date_added'] = pd.to_datetime('2003-04-01')
df_1.loc[df_1.index[9], 'date_added'] = pd.to_datetime('2012-10-31')

In [ ]:
df_1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2012-12-06,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,2013-04-14,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,2023-10-12,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,1994-09-22,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,2008-01-07,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,2003-12-22,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,2002-08-07,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2013-05-03,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2003-04-01,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,2012-10-31,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 6066 to 8182
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       10 non-null     object
 1   type          10 non-null     object
 2   title         10 non-null     object
 3   director      0 non-null      object
 4   cast          10 non-null     object
 5   country       9 non-null      object
 6   date_added    10 non-null     datetime64[ns]
 7   release_year  10 non-null     int64
 8   rating        10 non-null     object
 9   duration      10 non-null     object
 10  listed_in     10 non-null     object
 11  description   10 non-null     object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 1.3+ KB

In [ ]:
df_1['date_added']=pd.to_datetime(df_1['date_added'])

/tmp/ipykernel_726/443733938.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['date_added']=pd.to_datetime(df_1['date_added'])

In [ ]:
df = df.set_index('show_id')
df_1 = df_1.set_index('show_id')
df.update(df_1)
df = df.reset_index()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8807 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [ ]:
df['release_year'] = pd.to_datetime(df['release_year'], format='%Y').dt.year

In [ ]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country']=df['country'].fillna('Unknown')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8807 non-null   datetime64[ns]
 7   release_year  8807 non-null   int32
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int32(1), object(10)
memory usage: 791.4+ KB

In [ ]:
df_1 = df[df['rating'].isnull()]

In [ ]:
df_1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,Unknown,"Oprah Winfrey, Ava DuVernay",Unknown,2017-01-26,2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,Unknown,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,2016-12-01,2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,Unknown,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,2018-02-01,2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,2017-03-01,2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [ ]:
df_1.loc[df_1.index[0], 'rating'] = ('TV-MA')
df_1.loc[df_1.index[1], 'rating'] = ('TV-14')
df_1.loc[df_1.index[2], 'rating'] = ('G')
df_1.loc[df_1.index[3], 'rating'] = ('R')

In [ ]:
df_1

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,Unknown,"Oprah Winfrey, Ava DuVernay",Unknown,2017-01-26,2017,TV-MA,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,Unknown,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,2016-12-01,2013,TV-14,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,Unknown,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,2018-02-01,2015,G,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,2017-03-01,2015,R,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [ ]:
df = df.set_index('show_id')
df_1 = df_1.set_index('show_id')

In [ ]:
df.update(df_1)

/tmp/ipykernel_726/2766816723.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2020 2021 2021 ... 2009 2006 2015]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.update(df_1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8807 entries, s1 to s8807
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   object
 1   title         8807 non-null   object
 2   director      8807 non-null   object
 3   cast          8807 non-null   object
 4   country       8807 non-null   object
 5   date_added    8807 non-null   datetime64[ns]
 6   release_year  8807 non-null   int64
 7   rating        8807 non-null   object
 8   duration      8804 non-null   object
 9   listed_in     8807 non-null   object
 10  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 825.7+ KB

In [ ]:
df[df['duration'].isnull()]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,2016-09-16,2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,2016-08-15,2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [ ]:
df.loc['s5542', 'duration'] = '74 min'
df.loc['s5795', 'duration'] = '84 min'
df.loc['s5814', 'duration'] = '66 min'

In [ ]:
df.loc['s5542', 'rating'] = 'TV-MA'
df.loc['s5795', 'rating'] = 'TV-MA'
df.loc['s5814', 'rating'] = 'TV-MA'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8807 entries, s1 to s8807
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          8807 non-null   object
 1   title         8807 non-null   object
 2   director      8807 non-null   object
 3   cast          8807 non-null   object
 4   country       8807 non-null   object
 5   date_added    8807 non-null   datetime64[ns]
 6   release_year  8807 non-null   int64
 7   rating        8807 non-null   object
 8   duration      8807 non-null   object
 9   listed_in     8807 non-null   object
 10  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 1.1+ MB

In [ ]:
df.nunique()

type               2
title           8807
director        4529
cast            7693
country          749
date_added      1724
release_year      74
rating            14
duration         220
listed_in        514
description     8775
dtype: int64

In [ ]:
df['genres'] = df['listed_in'].str.split(',').str[0]

In [ ]:
df_1 = df[df['type']=="Movie"]
df_2 = df[df['type']!="Movie"]

In [ ]:
df_1

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,genres
show_id,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentaries
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,2021-09-24,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Children & Family Movies
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",Dramas
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,Comedies
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,Dramas
...,...,...,...,...,...,...,...,...,...,...,...,...
s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan",2016-03-09,2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,Dramas
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Cult Movies
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Comedies
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Children & Family Movies
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Dramas

In [ ]:
df_2

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,genres
show_id,,,,,,,,,,,,
s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",International TV Shows
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Crime TV Shows
s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Docuseries
s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,International TV Shows
s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",Unknown,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,TV Dramas
...,...,...,...,...,...,...,...,...,...,...,...,...
s8796,TV Show,Yu-Gi-Oh! Arc-V,Unknown,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada",2018-05-01,2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...,Anime Series
s8797,TV Show,Yunus Emre,Unknown,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves...",International TV Shows
s8798,TV Show,Zak Storm,Unknown,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia",2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...,Kids' TV
s8801,TV Show,Zindagi Gulzar Hai,Unknown,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre...",International TV Shows
s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",Kids' TV

In [ ]:
df_1['duration(min)'] = pd.to_numeric(df_1['duration'].str.extract('(\d+)', expand=False), errors='coerce').fillna(0).astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_726/3937237025.py:1: SyntaxWarning: invalid escape sequence '\d'
  df_1['duration(min)'] = pd.to_numeric(df_1['duration'].str.extract('(\d+)', expand=False), errors='coerce').fillna(0).astype(int)
/tmp/ipykernel_726/3937237025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['duration(min)'] = pd.to_numeric(df_1['duration'].str.extract('(\d+)', expand=False), errors='coerce').fillna(0).astype(int)

In [ ]:
df_1

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,genres,duration(min)
show_id,,,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Documentaries,90
s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",Unknown,2021-09-24,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,Children & Family Movies,91
s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",Dramas,125
s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,Comedies,104
s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,Dramas,127
...,...,...,...,...,...,...,...,...,...,...,...,...,...
s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan",2016-03-09,2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,Dramas,96
s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",Cult Movies,158
s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,Comedies,88
s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",Children & Family Movies,88
s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,Dramas,111

In [ ]:
df_1.describe()

                          date_added  release_year  duration(min)
count                           6131   6131.000000    6131.000000
mean   2019-05-07 03:32:47.639863040   2013.121514      99.564998
min              2008-01-01 00:00:00   1942.000000       3.000000
25%              2018-04-01 00:00:00   2012.000000      87.000000
50%              2019-06-19 00:00:00   2016.000000      98.000000
75%              2020-07-23 12:00:00   2018.000000     114.000000
max              2021-09-25 00:00:00   2021.000000     312.000000
std                              NaN      9.678169      28.289504

In [ ]:
df.genres.nunique()

36

In [ ]:
genre_counts = df.groupby('genres').size().reset_index()
genre_counts.rename(columns={0: 'count'}, inplace=True)
fig = px.bar(genre_counts, x='genres', y='count',
             title='Distribution of Content Over Different Genres',
             labels={'genres': 'Genre', 'count': 'Number of Titles'})
fig.show()

In [ ]:
a = df.groupby('release_year').size().reset_index()

In [ ]:
a

    release_year     0
0           1925     1
1           1942     2
2           1943     3
3           1944     3
4           1945     4
..           ...   ...
69          2017  1032
70          2018  1147
71          2019  1030
72          2020   953
73          2021   592

[74 rows x 2 columns]

In [ ]:
a.rename(columns={0: 'count'}, inplace=True)
fig = px.bar(a, x='release_year', y='count',
             title='Distribution of Content across Release Year',
             labels={'release_year': 'Release Year', 'count': 'Number of Titles'})
fig.show()

In [ ]:
df['country'] = df['country'].str.split(',').str[0]

In [ ]:
country_count = df.groupby('country').size().reset_index()
country_count.rename(columns={0:'count'},inplace=True)
country_count

         country  count
0                     2
1      Argentina     76
2      Australia    117
3        Austria      9
4     Bangladesh      3
..           ...    ...
82       Uruguay      9
83     Venezuela      2
84       Vietnam      7
85  West Germany      1
86      Zimbabwe      1

[87 rows x 2 columns]

In [ ]:
px.choropleth(country_count,locations=country_count['country'],locationmode='country names',projection='orthographic',color = country_count['count'])

In [ ]:
df['date_added'] = pd.to_datetime(df['date_added'])
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
monthly_counts = df.groupby(['year_added', 'month_added']).size().reset_index(name='count')
monthly_counts['DAY'] = 1
monthly_counts['Date'] = pd.to_datetime(monthly_counts[['year_added', 'month_added', 'DAY']].rename(columns={'year_added': 'year', 'month_added': 'month', 'DAY': 'day'}))
monthly_counts.set_index('Date', inplace=True)

In [ ]:
monthly_counts

            year_added  month_added  count  DAY
Date
1994-09-01        1994            9      1    1
2002-08-01        2002            8      1    1
2003-04-01        2003            4      1    1
2003-12-01        2003           12      1    1
2008-01-01        2008            1      2    1
...                ...          ...    ...  ...
2021-06-01        2021            6    207    1
2021-07-01        2021            7    257    1
2021-08-01        2021            8    178    1
2021-09-01        2021            9    183    1
2023-10-01        2023           10      1    1

[116 rows x 4 columns]

In [ ]:
fig = px.line(monthly_counts, x=monthly_counts.index, y='count',
             title='Content Added Over Time',
             labels={'Date': 'Date', 'count': 'Number of Titles Added'})
fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [ ]:
df['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'NR', 'TV-Y7-FV', 'UR'], dtype=object)

In [ ]:
rating_distribution=df.groupby(['rating','type']).size().reset_index(name='count')

In [ ]:
rating_distribution

      rating     type  count
0          G    Movie     41
1          G  TV Show      1
2      NC-17    Movie      3
3         NR    Movie     75
4         NR  TV Show      5
5         PG    Movie    287
6      PG-13    Movie    490
7          R    Movie    798
8          R  TV Show      2
9      TV-14    Movie   1427
10     TV-14  TV Show    734
11      TV-G    Movie    126
12      TV-G  TV Show     94
13     TV-MA    Movie   2066
14     TV-MA  TV Show   1145
15     TV-PG    Movie    540
16     TV-PG  TV Show    323
17      TV-Y    Movie    131
18      TV-Y  TV Show    176
19     TV-Y7    Movie    139
20     TV-Y7  TV Show    195
21  TV-Y7-FV    Movie      5
22  TV-Y7-FV  TV Show      1
23        UR    Movie      3

In [ ]:
fig = px.bar(rating_distribution,
             x='rating',
             y='count',
             color='type',
             barmode='group',
             title='Distribution of Content Ratings',
             labels={'rating': 'Rating', 'count': 'Number of Titles', 'type': 'Content Type'})
fig.show()

In [ ]:
df_1['duration(min)'].describe()

count    6131.000000
mean       99.564998
std        28.289504
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration(min), dtype: float64

In [ ]:
fig = px.histogram(df_1, x='duration(min)',
                   title='Distribution of Movie Lengths',
                   labels={'duration(min)': 'Movie Length (minutes)'})
fig.show()

In [ ]:
fig = px.box(df_1, x='release_year', y='duration(min)',
             title='Movie Length Trends Over Time',
             labels={'release_year': 'Release Year', 'duration(min)': 'Movie Length (minutes)'})
fig.show()

In [ ]:
rating_counts = df.groupby('rating').size().reset_index(name='count')
top_ratings = rating_counts.sort_values(by='count', ascending=False)
print(top_ratings)

      rating  count
8      TV-MA   3211
6      TV-14   2161
9      TV-PG    863
5          R    800
4      PG-13    490
11     TV-Y7    334
10      TV-Y    307
3         PG    287
7       TV-G    220
2         NR     80
0          G     42
12  TV-Y7-FV      6
1      NC-17      3
13        UR      3

In [ ]:
fig = px.bar(top_ratings, x='rating', y='count',
             title='Top Ratings (Proxy for User Ratings)',
             labels={'rating': 'Rating', 'count': 'Number of Titles'})
fig.show()

In [ ]:
genre_popularity_over_time = df.groupby(['release_year','genres']).size().reset_index(name='count')

In [ ]:
genre_popularity_over_time

     release_year          genres  count
0            1925        TV Shows      1
1            1942  Classic Movies      2
2            1943  Classic Movies      1
3            1943   Documentaries      2
4            1944  Classic Movies      3
..            ...             ...    ...
669          2021     TV Comedies     17
670          2021       TV Dramas      6
671          2021       TV Horror      1
672          2021        TV Shows      2
673          2021       Thrillers      4

[674 rows x 3 columns]

In [ ]:
fig = px.line(genre_popularity_over_time,
              x='release_year',
              y='count',
              color='genres',
              title='Popularity of Genres Over Time',
              labels={'release_year': 'Release Year', 'count': 'Number of Titles', 'genres': 'Genre'})
fig.show()

In [ ]:
country_genre_counts = df.groupby(['country', 'genres']).size().reset_index(name='count')

import plotly.express as px

fig = px.sunburst(country_genre_counts,
                  path=['country', 'genres'],
                  values='count',
                  title='Content Distribution Across Countries and Genres (Sunburst Chart)',
                  labels={'count': 'Number of Titles'})
fig.show()

In [ ]:
def top3_genres_by_country(df):

    country_genre_counts = df.groupby(['country', 'genres'])['genres'].count().reset_index(name='count')

    country_genre_counts = country_genre_counts.sort_values(['country', 'count'], ascending=[True, False])

    top3_genres = country_genre_counts.groupby('country').head(3)

    return top3_genres
top3_df = top3_genres_by_country(df)
print(top3_df)

          country                  genres  count
0                                  Dramas      1
1                  International TV Shows      1
10      Argentina                  Dramas     24
6       Argentina                Comedies      9
8       Argentina           Documentaries      8
..            ...                     ...    ...
583       Vietnam      Action & Adventure      2
586       Vietnam                  Dramas      2
584       Vietnam                Comedies      1
588  West Germany           Documentaries      1
589      Zimbabwe                Comedies      1

[210 rows x 3 columns]

In [ ]:
fig = px.bar(top3_df,
             x="country",
             y="count",
             color="genres",
             title="Top 3 Genres by Country",
             labels={"country": "Country", "count": "Number of Titles", "genres": "Genre"},
             barmode='stack')

fig.update_layout(xaxis_tickangle=-45)

fig.show()

In [ ]:
a= df.groupby('genres').size().sort_values(ascending=False).reset_index(name = 'count')

In [ ]:
a

                          genres  count
0                         Dramas   1600
1                       Comedies   1210
2             Action & Adventure    859
3                  Documentaries    829
4         International TV Shows    774
5       Children & Family Movies    605
6                 Crime TV Shows    399
7                       Kids' TV    388
8                Stand-Up Comedy    334
9                  Horror Movies    275
10              British TV Shows    253
11                    Docuseries    221
12                  Anime Series    176
13          International Movies    128
14                   TV Comedies    120
15                    Reality TV    120
16                Classic Movies     80
17                     TV Dramas     67
18                     Thrillers     65
19                        Movies     57
20         TV Action & Adventure     40
21  Stand-Up Comedy & Talk Shows     34
22             Romantic TV Shows     32
23             Classic & Cult TV     22
24                Anime Features     21
25            Independent Movies     20
26              Music & Musicals     18
27                      TV Shows     16
28              Sci-Fi & Fantasy     13
29                   Cult Movies     12
30                     TV Horror     11
31               Romantic Movies      3
32     Spanish-Language TV Shows      2
33                  LGBTQ Movies      1
34                 Sports Movies      1
35           TV Sci-Fi & Fantasy      1

In [ ]:
px.bar(a,x="genres", y="count",title="Count of different Genres",labels={"genres": "Genres", "count": "Count"})

In [ ]:
genre_popularity = df.groupby('genres').size().reset_index(name='count')
genre_popularity = genre_popularity.sort_values(by='count', ascending=False)
print(genre_popularity)

                          genres  count
12                        Dramas   1600
7                       Comedies   1210
0             Action & Adventure    859
10                 Documentaries    829
16        International TV Shows    774
4       Children & Family Movies    605
8                 Crime TV Shows    399
17                      Kids' TV    388
27               Stand-Up Comedy    334
13                 Horror Movies    275
3               British TV Shows    253
11                    Docuseries    221
2                   Anime Series    176
15          International Movies    128
30                   TV Comedies    120
21                    Reality TV    120
6                 Classic Movies     80
31                     TV Dramas     67
35                     Thrillers     65
19                        Movies     57
29         TV Action & Adventure     40
28  Stand-Up Comedy & Talk Shows     34
23             Romantic TV Shows     32
5              Classic & Cult TV     22
1                 Anime Features     21
14            Independent Movies     20
20              Music & Musicals     18
34                      TV Shows     16
24              Sci-Fi & Fantasy     13
9                    Cult Movies     12
32                     TV Horror     11
22               Romantic Movies      3
25     Spanish-Language TV Shows      2
18                  LGBTQ Movies      1
26                 Sports Movies      1
33           TV Sci-Fi & Fantasy      1

In [ ]:
fig = px.bar(genre_popularity, x='genres', y='count',
             title='Popularity of Genres',
             labels={'genres': 'Genre', 'count': 'Number of Titles'})
fig.show()

In [ ]:
type_popularity = df.groupby('type').size().reset_index(name='count')
type_popularity = type_popularity.sort_values(by='count', ascending=False)
print(type_popularity)

      type  count
0    Movie   6131
1  TV Show   2676

In [ ]:
fig = px.bar(type_popularity, x='type', y='count',
             title='Popularity of Content Types',
             labels={'type': 'Content Type', 'count': 'Number of Titles'},
             color = 'type')
fig.show()